# Broadcasting

In [ ]:
import numpy as np

In [6]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2, 7, 5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [7]:
# shape
my_3D_array.shape

(2, 7, 5)

In [8]:
# number of dimensions
my_3D_array.ndim

3

In [10]:
# size; number of elements
my_3D_array.size

70

In [11]:
# data type for each element
my_3D_array.dtype

dtype('int64')

In [12]:
5 * my_3D_array -2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [14]:
left_mat = np.arange(6).reshape((2, 3))
right_mat = np.arange(15).reshape((3, 5))

In [15]:
np.inner(left_mat, right_mat)

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [16]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

### Operations along axes

In [17]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [18]:
my_3D_array.shape

(2, 7, 5)

In [20]:
# sum all numbers in an array
my_3D_array.sum()

2415

In [21]:
# 
(69 * 70)/2

2415.0

In [22]:
my_3D_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [23]:
my_3D_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [24]:
my_3D_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting rules

In [27]:
# two or more arrays
my_2D_array = np.ones(35, dtype='int_').reshape((7,5)) * 3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [28]:
my_random_2D_array = np.random.random((7,5))
np.set_printoptions(precision=4)
my_3D_array* my_random_2D_array

array([[[0.0000e+00, 3.5570e-03, 1.8690e+00, 2.5465e+00, 3.3943e+00],
        [2.4577e+00, 5.3349e+00, 6.0649e+00, 1.4618e+00, 5.2560e-01],
        [1.8482e+00, 5.2319e+00, 9.9291e+00, 4.6981e+00, 6.2573e+00],
        [4.5467e-01, 1.4688e+01, 1.6221e+01, 1.2558e+01, 1.7608e+01],
        [6.5641e+00, 9.6377e-01, 1.0327e+01, 6.4455e+00, 6.2868e+00],
        [3.3776e+00, 1.9271e+01, 1.2542e+01, 1.9683e+01, 1.2766e+01],
        [3.0108e+00, 9.6427e-01, 2.1882e+01, 2.9688e+01, 2.8014e+01]],

       [[3.3382e+01, 1.2805e-01, 3.4576e+01, 3.2256e+01, 3.3095e+01],
        [1.9662e+01, 3.6455e+01, 3.6389e+01, 7.8572e+00, 2.5696e+00],
        [8.3169e+00, 2.1879e+01, 3.8889e+01, 1.7347e+01, 2.1901e+01],
        [1.5156e+00, 4.6818e+01, 4.9616e+01, 3.6976e+01, 5.0043e+01],
        [1.8051e+01, 2.5701e+00, 2.6757e+01, 1.6254e+01, 1.5455e+01],
        [8.1062e+00, 4.5213e+01, 2.8799e+01, 4.4287e+01, 2.8173e+01],
        [6.5234e+00, 2.0530e+00, 4.5816e+01, 6.1176e+01, 5.6853e+01]]])

In [31]:
my_vector = np.arange(5)*7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [32]:
my_3D_array/my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [33]:
my_3D_array%my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]])